package learnJava.rz20200307;

import java.util.HashMap;

public class ClassMainData {
	public static HashMap<String, String> JdkVersion = new HashMap<String, String>();
	public static HashMap<String, String> Costanst_map = new HashMap<String, String>();
	public static HashMap<Integer, String> AccFlag_map = new HashMap<Integer, String>();
	public static HashMap<String, String> Jvm_map = new HashMap<String, String>();
	//	public static HashMap<String, String> Costanst_map = new HashMap<String, String>();
	
	static {
		JdkVersion.put("46", "jdk1.2");
		JdkVersion.put("47", "jdk1.3");
		JdkVersion.put("48", "jdk1.4");
		JdkVersion.put("49", "jdk1.5");
		JdkVersion.put("50", "jdk1.6");
		JdkVersion.put("51", "jdk1.7");
		JdkVersion.put("52", "jdk1.8");
		Costanst_map.put("1", "CONSTANT_Utf8_info");
		Costanst_map.put("3", "CONSTANT_Integer_info");
		Costanst_map.put("4", "CONSTATN_Float_info");
		Costanst_map.put("5", "CONSTANT_Long_info");
		Costanst_map.put("6", "CONSTANT_Double_info");
		Costanst_map.put("7", "CONSTANT_Class_info");
		Costanst_map.put("8", "CONSTANT_String_info");
		Costanst_map.put("9", "CONSTANT_Fieldref_info");
		Costanst_map.put("10", "CONSTANT_Methodref_info");
		Costanst_map.put("11", "CONSTANT_InterfaceMethodref_info");
		Costanst_map.put("12", "CONSTANT_NameAndType_info");
		Costanst_map.put("15", "CONSTANT_MethodHandler_info");
		Costanst_map.put("16", "CONSTANT_MethodType_info");
		Costanst_map.put("17", "CONSTANT_Dynamic_info");
		Costanst_map.put("18", "CONSTANT_InvokeDynamic_info");
		Costanst_map.put("19", "CONSTANT_Module_info");
		Costanst_map.put("20", "CONSTANT_Package_info");
		Costanst_map.put("CONSTANT_Utf8_info", "1,2,1");
		Costanst_map.put("CONSTANT_Integer_info", "1,4");
		Costanst_map.put("CONSTATN_Float_info", "1,4");
		Costanst_map.put("CONSTANT_Long_info", "1,8");
		Costanst_map.put("CONSTANT_Double_info", "1,8");
		Costanst_map.put("CONSTANT_Class_info", "1,2");
		Costanst_map.put("CONSTANT_String_info", "1,2");
		Costanst_map.put("CONSTANT_Fieldref_info", "1,2,2");
		Costanst_map.put("CONSTANT_Methodref_info", "1,2,2");
		Costanst_map.put("CONSTANT_InterfaceMethodref_info", "1,2,2");
		Costanst_map.put("CONSTANT_NameAndType_info", "1,2,2");
		Costanst_map.put("CONSTANT_MethodHandler_info", "1,1,2");
		Costanst_map.put("CONSTANT_MethodType_info", "1,2");
		Costanst_map.put("CONSTANT_Dynamic_info", "1,2,2");
		
		AccFlag_map.put(0x0001,"ACC_PUBLIC");
		AccFlag_map.put(0x0002,"ACC_PRIVATE");
		AccFlag_map.put(0x0010,"ACC_FINAL");
		AccFlag_map.put(0x0020,"ACC_SUPER");
		AccFlag_map.put(0x0200,"ACC_INERFACE");
		AccFlag_map.put(0x0400,"ACC_ABSTRACT");
		AccFlag_map.put(0x1000,"ACC_SYNTHETIC");
		AccFlag_map.put(0x2000,"ACC_ANNOTATION");
		AccFlag_map.put(0x4000,"ACC_ENUM");
		
		Jvm_map.put("0x00","nop");
		Jvm_map.put("0x01","aconst_null ");
		Jvm_map.put("0x02","iconst_m1");
		Jvm_map.put("0x03","iconst_0");
		Jvm_map.put("0x04","iconst_1");
		Jvm_map.put("0x05","iconst_2");
		Jvm_map.put("0x06","iconst_3");
		Jvm_map.put("0x07","iconst_4");
		Jvm_map.put("0x08","iconst_5");
		Jvm_map.put("0x09","lconst_0");
		Jvm_map.put("0x0a","lconst_1");
		Jvm_map.put("0x0b","fconst_0");
		Jvm_map.put("0x0c","fconst_1");
		Jvm_map.put("0x0d","fconst_2");
		Jvm_map.put("0x0e","dconst_0");
		Jvm_map.put("0x0f","dconst_1");
		Jvm_map.put("0x10","bipush");
		Jvm_map.put("0x11","sipush");
		Jvm_map.put("0x12","ldc");
		Jvm_map.put("0x13","ldc_w");
		Jvm_map.put("0x14","ldc2_w");
		Jvm_map.put("0x15","iload");
		Jvm_map.put("0x16","lload");
		Jvm_map.put("0x17","fload");
		Jvm_map.put("0x18","dload");
		Jvm_map.put("0x19","aload");
		Jvm_map.put("0x1a","iload_0");
		Jvm_map.put("0x1b","iload_1");
		Jvm_map.put("0x1c","iload_2");
		Jvm_map.put("0x1d","iload_3");
		Jvm_map.put("0x1e","lload_0");
		Jvm_map.put("0x1f","lload_1");
		Jvm_map.put("0x20","lload_2");
		Jvm_map.put("0x21","lload_3");
		Jvm_map.put("0x22","fload_0");
		Jvm_map.put("0x23","fload_1");
		Jvm_map.put("0x24","fload_2");
		Jvm_map.put("0x25","fload_3");
		Jvm_map.put("0x26","dload_0");
		Jvm_map.put("0x27","dload_1");
		Jvm_map.put("0x28","dload_2");
		Jvm_map.put("0x29","dload_3");
		Jvm_map.put("0x2a","aload_0");
		Jvm_map.put("0x2b","aload_1");
		Jvm_map.put("0x2c","aload_2");
		Jvm_map.put("0x2d","aload_3");
		Jvm_map.put("0x2e","iaload");
		Jvm_map.put("0x2f","laload");
		Jvm_map.put("0x30","faload");
		Jvm_map.put("0x31","daload");
		Jvm_map.put("0x32","aaload");
		Jvm_map.put("0x33","baload");
		Jvm_map.put("0x34","caload");
		Jvm_map.put("0x35","saload");
		Jvm_map.put("0x36","istore");
		Jvm_map.put("0x37","lstore");
		Jvm_map.put("0x38","fstore");
		Jvm_map.put("0x39","dstore");
		Jvm_map.put("0x3a","astore");
		Jvm_map.put("0x3b","istore_0");
		Jvm_map.put("0x3c","istore_1");
		Jvm_map.put("0x3d","istore_2");
		Jvm_map.put("0x3e","istore_3");
		Jvm_map.put("0x3f","lstore_0");
		Jvm_map.put("0x40","lstore_1");
		Jvm_map.put("0x41","lstore_2");
		Jvm_map.put("0x42","lstore_3");
		Jvm_map.put("0x43","fstore_0");
		Jvm_map.put("0x44","fstore_1");
		Jvm_map.put("0x45","fstore_2");
		Jvm_map.put("0x46","fstore_3");
		Jvm_map.put("0x47","dstore_0");
		Jvm_map.put("0x48","dstore_1");
		Jvm_map.put("0x49","dstore_2");
		Jvm_map.put("0x4a","dstore_3");
		Jvm_map.put("0x4b","astore_0");
		Jvm_map.put("0x4c","astore_1");
		Jvm_map.put("0x4d","astore_2");
		Jvm_map.put("0x4e","astore_3");
		Jvm_map.put("0x4f","iastore");
		Jvm_map.put("0x50","lastore");
		Jvm_map.put("0x51","fastore");
		Jvm_map.put("0x52","dastore");
		Jvm_map.put("0x53","aastore");
		Jvm_map.put("0x54","bastore");
		Jvm_map.put("0x55","castore");
		Jvm_map.put("0x56","sastore");
		Jvm_map.put("0x57","pop");
		Jvm_map.put("0x58","pop2");
		Jvm_map.put("0x59","dup");
		Jvm_map.put("0x5a","dup_x1");
		Jvm_map.put("0x5b","dup_x2");
		Jvm_map.put("0x5c","dup2");
		Jvm_map.put("0x5d","dup2_x1");
		Jvm_map.put("0x5e","dup2_x2");
		Jvm_map.put("0x5f","swap");
		Jvm_map.put("0x60","iadd");
		Jvm_map.put("0x61","ladd");
		Jvm_map.put("0x62","fadd");
		Jvm_map.put("0x63","dadd");
		Jvm_map.put("0x64","isub");
		Jvm_map.put("0x65","lsub");
		Jvm_map.put("0x66","fsub");
		Jvm_map.put("0x67","dsub");
		Jvm_map.put("0x68","imul");
		Jvm_map.put("0x69","lmul");
		Jvm_map.put("0x6a","fmul");
		Jvm_map.put("0x6b","dmul");
		Jvm_map.put("0x6c","idiv");
		Jvm_map.put("0x6d","ldiv");
		Jvm_map.put("0x6e","fdiv");
		Jvm_map.put("0x6f","ddiv");
		Jvm_map.put("0x70","irem");
		Jvm_map.put("0x71","lrem");
		Jvm_map.put("0x72","frem");
		Jvm_map.put("0x73","drem");
		Jvm_map.put("0x74","ineg");
		Jvm_map.put("0x75","lneg");
		Jvm_map.put("0x76","fneg");
		Jvm_map.put("0x77","dneg");
		Jvm_map.put("0x78","ishl");
		Jvm_map.put("0x79","lshl");
		Jvm_map.put("0x7a","ishr");
		Jvm_map.put("0x7b","lshr");
		Jvm_map.put("0x7c","iushr");
		Jvm_map.put("0x7d","lushr");
		Jvm_map.put("0x7e","iand");
		Jvm_map.put("0x7f","land");
		Jvm_map.put("0x80","ior");
		Jvm_map.put("0x81","lor");
		Jvm_map.put("0x82","ixor");
		Jvm_map.put("0x83","lxor");
		Jvm_map.put("0x84","iinc");
		Jvm_map.put("0x85","i2l");
		Jvm_map.put("0x86","i2f");
		Jvm_map.put("0x87","i2d");
		Jvm_map.put("0x88","l2i");
		Jvm_map.put("0x89","l2f");
		Jvm_map.put("0x8a","l2d");
		Jvm_map.put("0x8b","f2i");
		Jvm_map.put("0x8c","f2l");
		Jvm_map.put("0x8d","f2d");
		Jvm_map.put("0x8e","d2i");
		Jvm_map.put("0x8f","d2l");
		Jvm_map.put("0x90","d2f");
		Jvm_map.put("0x91","i2b");
		Jvm_map.put("0x92","i2c");
		Jvm_map.put("0x93","i2s");
		Jvm_map.put("0x94","lcmp");
		Jvm_map.put("0x95","fcmpl");
		Jvm_map.put("0x96","fcmpg");
		Jvm_map.put("0x97","dcmpl");
		Jvm_map.put("0x98","dcmpg");
		Jvm_map.put("0x99","ifeq");
		Jvm_map.put("0x9a","ifne");
		Jvm_map.put("0x9b","iflt");
		Jvm_map.put("0x9c","ifge");
		Jvm_map.put("0x9d","ifgt");
		Jvm_map.put("0x9e","ifle");
		Jvm_map.put("0x9f","if_icmpeq");
		Jvm_map.put("0xa0","if_icmpne");
		Jvm_map.put("0xa1","if_icmplt");
		Jvm_map.put("0xa2","if_icmpge");
		Jvm_map.put("0xa3","if_icmpgt");
		Jvm_map.put("0xa4","if_icmple");
		Jvm_map.put("0xa5","if_acmpeq");
		Jvm_map.put("0xa6","if_acmpne");
		Jvm_map.put("0xa7","goto");
		Jvm_map.put("0xa8","jsr");
		Jvm_map.put("0xa9","ret");
		Jvm_map.put("0xaa","tableswitch");
		Jvm_map.put("0xab","lookupswitch");
		Jvm_map.put("0xac","ireturn");
		Jvm_map.put("0xad","lreturn");
		Jvm_map.put("0xae","freturn");
		Jvm_map.put("0xaf","dreturn");
		Jvm_map.put("0xb0","areturn");
		Jvm_map.put("0xb1","return");
		Jvm_map.put("0xb2","getstatic");
		Jvm_map.put("0xb3","putstatic");
		Jvm_map.put("0xb4","getfield");
		Jvm_map.put("0xb5","putfield");
		Jvm_map.put("0xb6","invokevirtual");
		Jvm_map.put("0xb7","invokespecial");
		Jvm_map.put("0xb8","invokestatic");
		Jvm_map.put("0xb9","invokeinterface0xba invokedynamic0xbb new");
		Jvm_map.put("0xbc","newarray");
		Jvm_map.put("0xbd","anewarray");
		Jvm_map.put("0xbe","arraylength0xbf athrow");
		Jvm_map.put("0xc0","checkcast");
		Jvm_map.put("0xc1","instanceof1 ");
		Jvm_map.put("0xc2","monitorenter");
		Jvm_map.put("0xc3","monitorexit");
		Jvm_map.put("0xc4","wide");
		Jvm_map.put("0xc5","multianewarray0xc6 ifnull");
		Jvm_map.put("0xc7","ifnonnull");
		Jvm_map.put("0xc8","goto_w");
		Jvm_map.put("0xc9","jsr_w");
		Jvm_map.put("0xca","breakpoint0xfe impdep1");
		Jvm_map.put("0xff","impdep2");
		
	}
	
	public static class AcessFlag {
		public static final int ACC_PUBLIC = 0x0001;
		public static final int ACC_FINAL = 0x0010;
		public static final int ACC_SUPER = 0x0020;
		public static final int ACC_INERFACE = 0x0200;
		public static final int ACC_ABSTRACT = 0x0400;
		public static final int ACC_SYNTHETIC = 0x1000;
		public static final int ACC_ANNOTATION = 0x2000;
		public static final int ACC_ENUM = 0x4000;
	}
}
